# Generated by Django 3.2.3 on 2021-06-14 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aptos_rent', '0002_auto_20210528_0016'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manage',
            fields=[
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manage_apto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='aptos_rent.aptos')),
                ('status', models.CharField(choices=[('Not started', 'Not started'), ('In progress', 'In progress'), ('Finished', 'Finished')], max_length=11)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
