# Generated by Django 3.2.3 on 2021-06-14 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aptos_rent', '0003_manage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aptos',
            name='bedrooms',
            field=models.PositiveSmallIntegerField(help_text='Número de Habitaciones'),
        ),
        migrations.AlterField(
            model_name='aptos',
            name='flat',
            field=models.PositiveSmallIntegerField(help_text='Número de piso'),
        ),
        migrations.AlterField(
            model_name='aptos',
            name='score_address',
            field=models.PositiveSmallIntegerField(choices=[(20, 'Jmmmm'), (40, 'Lejana'), (60, 'Pasable'), (80, 'Muy buena'), (100, 'Perfecta')]),
        ),
        migrations.AlterField(
            model_name='aptos',
            name='score_backyard',
            field=models.PositiveSmallIntegerField(choices=[(40, 'Pequeña'), (70, 'Mediana'), (100, 'Grande')]),
        ),
        migrations.AlterField(
            model_name='aptos',
            name='score_dining_room',
            field=models.PositiveSmallIntegerField(choices=[(40, 'Pequeña'), (70, 'Mediana'), (100, 'Grande')]),
        ),
        migrations.AlterField(
            model_name='aptos',
            name='socre_kitchen',
            field=models.PositiveSmallIntegerField(choices=[(20, 'Mmmmm'), (40, 'De pronto'), (60, 'Pasable'), (80, 'Muy buena'), (100, 'Perfecta')]),
        ),
        migrations.AlterField(
            model_name='aptos',
            name='toilets',
            field=models.PositiveSmallIntegerField(help_text='Número de baños'),
        ),
        migrations.AlterField(
            model_name='manage',
            name='status',
            field=models.CharField(choices=[('Not started', 'Not started'), ('In progress', 'In progress'), ('Finished', 'Finished')], default='Not started', max_length=11),
        ),
    ]
