# Generated by Django 3.2.3 on 2021-06-15 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aptos_rent', '0006_aptos_updated_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Manage',
        ),
    ]
